name: Main - CurseForge - Package and Release - All pushes

# Deploy on all pushes to master, except '.github/**' folder.
on:
  push:
    branches:
      - master
    tags:
      - '*'
      - '!**-alpha**'
    paths-ignore:
      - '.github/**'

jobs:

  build-and-publish:
  
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow
                                                 # for your own token, the name cannot start with "GITHUB_"

    steps:
    
      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 100 # for automated history

      - name: Package and Release
        uses: BigWigsMods/packager@master
        #continue-on-error: true
        with:
          args: -S -o